project:
  type: website

website:
  title: "Islam Gabdulkayum"
  navbar:
    left:
      - text: "R Studio Project Page"
        href: Final_assignment_Islam_G.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    code-fold: true
    theme-variables:
      bg: "#FFE5B4"
      heading-color: "#FF8C00"
      primary-color: "#FF8C00"
      font-heading: "Georgia"
      font-body: "Arial"